language: node_js
node_js:
  - '0.12'
  - 'iojs'
before_script:
  - 'npm install -g grunt-cli'
  - 'npm install -g mocha'
  - 'mocha test/**/*.js'
  - 'grunt travis'
deploy:
  provider: heroku
  api_key: "686470c8-1bd9-46f5-a635-b287bc7ccdb7"
  app: rtc-socketio-benchmarking